INFO:root:*********partition data***************
download = True
Using downloaded and verified file: ./../../../data/cifar10/cifar-10-python.tar.gz
Traceback (most recent call last):
  File "/home/whiteashes/Project/FedML/fedml_experiments/standalone/fedavg/main_fedavg.py", line 304, in <module>
    dataset = load_data(args, args.dataset)
  File "/home/whiteashes/Project/FedML/fedml_experiments/standalone/fedavg/main_fedavg.py", line 205, in load_data
    args.partition_alpha, args.client_num_in_total, args.batch_size)
  File "/home/whiteashes/Project/FedML/fedml_api/data_preprocessing/cifar10/data_loader.py", line 240, in load_partition_data_cifar10
    partition_alpha)
  File "/home/whiteashes/Project/FedML/fedml_api/data_preprocessing/cifar10/data_loader.py", line 115, in partition_data
    X_train, y_train, X_test, y_test = load_cifar10_data(datadir)
  File "/home/whiteashes/Project/FedML/fedml_api/data_preprocessing/cifar10/data_loader.py", line 104, in load_cifar10_data
    cifar10_train_ds = CIFAR10_truncated(datadir, train=True, download=True, transform=train_transform)
  File "/home/whiteashes/Project/FedML/fedml_api/data_preprocessing/cifar10/datasets.py", line 50, in __init__
    self.data, self.target = self.__build_truncated_dataset__()
  File "/home/whiteashes/Project/FedML/fedml_api/data_preprocessing/cifar10/datasets.py", line 59, in __build_truncated_dataset__
    data = cifar_dataobj.data
AttributeError: 'CIFAR10' object has no attribute 'data'
