2021-01-15 14:47:48,696 INFO    MainThread:1335856 [wandb_setup.py:_flush():70] setting env: {}
2021-01-15 14:47:48,696 INFO    MainThread:1335856 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-01-15 14:47:48,696 INFO    MainThread:1335856 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-15 14:47:48,696 INFO    MainThread:1335856 [wandb_init.py:_log_setup():318] Logging user logs to /home/whiteashes/Project/FedML/fedml_experiments/standalone/fedavg/wandb/run-20210115_144748-289vks82/logs/debug.log
2021-01-15 14:47:48,696 INFO    MainThread:1335856 [wandb_init.py:_log_setup():319] Logging internal logs to /home/whiteashes/Project/FedML/fedml_experiments/standalone/fedavg/wandb/run-20210115_144748-289vks82/logs/debug-internal.log
2021-01-15 14:47:50,456 INFO    MainThread:1335856 [wandb_run.py:_console_start():1308] atexit reg
2021-01-15 14:47:50,456 INFO    MainThread:1335856 [wandb_run.py:_redirect():1175] redirect: SettingsConsole.REDIRECT
2021-01-15 14:47:50,457 INFO    MainThread:1335856 [wandb_run.py:_redirect():1178] Redirecting console.
2021-01-15 14:47:50,457 INFO    MainThread:1335856 [redirect.py:install():205] install start
2021-01-15 14:47:50,457 INFO    MainThread:1335856 [redirect.py:install():220] install stop
2021-01-15 14:47:50,457 INFO    MainThread:1335856 [redirect.py:install():205] install start
2021-01-15 14:47:50,457 INFO    MainThread:1335856 [redirect.py:install():220] install stop
2021-01-15 14:47:50,457 INFO    MainThread:1335856 [wandb_run.py:_redirect():1222] Redirects installed.
2021-01-15 14:48:01,567 INFO    MainThread:1335856 [wandb_run.py:_atexit_cleanup():1278] got exitcode: 255
2021-01-15 14:48:01,567 INFO    MainThread:1335856 [wandb_run.py:_restore():1250] restore
2021-01-15 14:48:01,567 INFO    MainThread:1335856 [redirect.py:uninstall():224] uninstall start
2021-01-15 14:48:01,568 INFO    MainThread:1335856 [redirect.py:_stop():279] _stop: stdout
2021-01-15 14:48:01,568 ERROR   stderr    :1335856 [redirect.py:_pipe_relay():131] problem in pipe relay
Traceback (most recent call last):
  File "/home/whiteashes/anaconda3/envs/fedml/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 129, in _pipe_relay
    cb(name, data)
  File "/home/whiteashes/anaconda3/envs/fedml/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 664, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "/home/whiteashes/anaconda3/envs/fedml/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 151, in publish_output
    self._publish_output(o)
  File "/home/whiteashes/anaconda3/envs/fedml/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 156, in _publish_output
    self._publish(rec)
  File "/home/whiteashes/anaconda3/envs/fedml/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 455, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2021-01-15 14:48:01,568 INFO    MainThread:1335856 [redirect.py:_stop():285] _stop closed: stdout
2021-01-15 14:48:01,568 INFO    stdout    :1335856 [redirect.py:_pipe_relay():121] relay done saw last write: stdout
2021-01-15 14:48:01,569 INFO    stdout    :1335856 [redirect.py:_pipe_relay():137] relay done done: stdout
2021-01-15 14:48:01,569 INFO    MainThread:1335856 [redirect.py:_stop():291] _stop joined: stdout
2021-01-15 14:48:01,569 INFO    MainThread:1335856 [redirect.py:_stop():293] _stop rd closed: stdout
2021-01-15 14:48:01,569 INFO    MainThread:1335856 [redirect.py:uninstall():228] uninstall done
2021-01-15 14:48:01,569 INFO    MainThread:1335856 [redirect.py:uninstall():224] uninstall start
2021-01-15 14:48:01,569 INFO    MainThread:1335856 [redirect.py:_stop():279] _stop: stderr
2021-01-15 14:48:01,569 INFO    stderr    :1335856 [redirect.py:_pipe_relay():121] relay done saw last write: stderr
2021-01-15 14:48:01,569 INFO    stderr    :1335856 [redirect.py:_pipe_relay():137] relay done done: stderr
2021-01-15 14:48:01,569 INFO    MainThread:1335856 [redirect.py:_stop():285] _stop closed: stderr
2021-01-15 14:48:01,569 INFO    MainThread:1335856 [redirect.py:_stop():291] _stop joined: stderr
2021-01-15 14:48:01,569 INFO    MainThread:1335856 [redirect.py:_stop():293] _stop rd closed: stderr
2021-01-15 14:48:01,569 INFO    MainThread:1335856 [redirect.py:uninstall():228] uninstall done
2021-01-15 14:48:01,569 INFO    MainThread:1335856 [wandb_run.py:_restore():1250] restore
